# source will be downloaded prior to filling in jinja templates
# Example assumes that this folder has setup.py in it
source:
  path: ..

package:
  name: microdrop-plugin-manager
  version: 0.8.3.alpha
build:
  entry_points:
    - mpm = mpm.bin:main
    - microdrop-plugin-build = mpm.bin.build:main
    - microdrop-plugin-api = mpm.bin.api:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    #: ..versionchanged:: 0.25.1
    - conda-helpers
    - configobj
    - path-helpers
    - pint
    - paver
    - progressbar2
    - pywin32  # [win]
    - pyyaml
    - si-prefix

  run:
    #: ..versionchanged:: 0.25.1
    - conda-helpers
    - configobj
    - git
    - progressbar2
    - pywin32  # [win]
    - pyyaml
    - requests
    - si-prefix
    - versioneer
    - ntfsutils
    - natsort

test:
  imports:
    - mpm.api
    - mpm.commands
    - mpm.hooks
